name: CI Workflow

on: push
#  pull_request:
#    branches:
#      - main
##      - foltrex/dev
#  workflow_dispatch:

jobs:
  build:
    name: Build with Maven
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'

      - name: Test with Maven
        run: ./mvnw '-Dtest=by.bsu.jimba.*.*Tests' test

#      - name: Compile with Maven
#        run: ./mvnw clean compile